name: Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  client-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test:coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: client-coverage
          path: coverage

  server-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -m pip install --upgrade pip
      - run: pip install pytest pytest-cov
      - run: pytest --cov=app --cov-report=xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: server-coverage
          path: coverage.xml

  merge-coverage:
    runs-on: ubuntu-latest
    needs: [client-coverage, server-coverage]
    steps:
      - uses: actions/checkout@v2
      - name: Download client coverage
        uses: actions/download-artifact@v2
        with:
          name: client-coverage
          path: ./coverage/client
      - name: Download server coverage
        uses: actions/download-artifact@v2
        with:
          name: server-coverage
          path: ./coverage/server
      - name: Merge coverage reports
        run: |
          pip install coverage
          coverage combine ./coverage/client ./coverage/server
          coverage report
          coverage xml
      - name: Upload merged coverage report
        uses: actions/upload-artifact@v2
        with:
          name: merged-coverage
          path: coverage.xml